#!/bin/csh
#

set init = step5_input
set equi_prefix = step6.%d_equilibration
set prod_prefix = step7_production
set prod_step   = step7

# Equilibration
set cnt = 1
while ( ${cnt} <= 6 )
    @ pcnt = ${cnt} - 1
    set istep = `printf ${equi_prefix} ${cnt}`
    set pstep = `printf ${equi_prefix} ${pcnt}`
    set input_param = "-t toppar.str -p ${init}.psf -c ${init}.crd"
    if ( ${cnt} == 1 ) set input_param = `echo "${input_param} -b sysinfo.dat"`
    if ( ${cnt} != 1 ) set input_param = `echo "${input_param} -irst ${pstep}.rst"`
    python -u plumed_OpenMM.py -i ${istep}.inp Equilibration.pdb -opdb  -orst ${istep}.rst -odcd Equilibration.dcd > Equilibration.out
    @ cnt += 1
end

# Production
# The OpenMM check point file (.chk) cannot be used in a different machine environment.
# So please make sure if you are using the same GPU and CUDA version of machine while doing additional
# production steps with the check point file.


set input_param = "-t toppar.str -p ${init}.psf -c ${init}.crd -irst ${pstep}.rst"
python -u plumed_OpenMM.py -i ${prod_prefix}.inp ${input_param} -orst ${istep}.rst -odcd Production.dcd > ${istep}.out
 


